-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 13:09:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aceitunas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aceitunas` ;

-- -----------------------------------------------------
-- Schema aceitunas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aceitunas` ;
USE `aceitunas` ;

-- -----------------------------------------------------
-- Table `aceitunas`.`aceituna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`aceituna` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`aceituna` (
  `aceituna_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT 'manzanilla',
  `peso` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`aceituna_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`ciudad` (
  `ciudad_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ciudad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`jugador` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`jugador` (
  `jugador_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `ciudad_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`jugador_id`),
  INDEX `fk_jugador_ciudad1_idx` (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `aceitunas`.`ciudad` (`ciudad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`torneo` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`torneo` (
  `torneo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `aceituna_id` INT UNSIGNED NOT NULL,
  `ciudad_id` INT UNSIGNED NOT NULL,
  `ganador_id` INT UNSIGNED NULL,
  PRIMARY KEY (`torneo_id`),
  UNIQUE INDEX `NOMBRE_FECHA_UQ` (`nombre` ASC, `fecha` ASC) VISIBLE,
  INDEX `fk_torneo_aceituna_idx` (`aceituna_id` ASC) VISIBLE,
  INDEX `fk_torneo_ciudad1_idx` (`ciudad_id` ASC) VISIBLE,
  INDEX `fk_torneo_jugador1_idx` (`ganador_id` ASC) VISIBLE,
  CONSTRAINT `fk_torneo_aceituna`
    FOREIGN KEY (`aceituna_id`)
    REFERENCES `aceitunas`.`aceituna` (`aceituna_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `aceitunas`.`ciudad` (`ciudad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneo_jugador1`
    FOREIGN KEY (`ganador_id`)
    REFERENCES `aceitunas`.`jugador` (`jugador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`partida` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`partida` (
  `partida_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `torneo_id` INT UNSIGNED NOT NULL,
  `finalizada` BIT NULL DEFAULT 0,
  `ganador_id` INT UNSIGNED NULL,
  PRIMARY KEY (`partida_id`),
  INDEX `fk_partida_torneo1_idx` (`torneo_id` ASC) VISIBLE,
  INDEX `fk_partida_jugador1_idx` (`ganador_id` ASC) VISIBLE,
  CONSTRAINT `fk_partida_torneo1`
    FOREIGN KEY (`torneo_id`)
    REFERENCES `aceitunas`.`torneo` (`torneo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partida_jugador1`
    FOREIGN KEY (`ganador_id`)
    REFERENCES `aceitunas`.`jugador` (`jugador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`partida_has_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`partida_has_jugador` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`partida_has_jugador` (
  `partida_id` INT UNSIGNED NOT NULL,
  `jugador_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`partida_id`, `jugador_id`),
  INDEX `fk_partida_has_jugador_jugador1_idx` (`jugador_id` ASC) VISIBLE,
  INDEX `fk_partida_has_jugador_partida1_idx` (`partida_id` ASC) VISIBLE,
  CONSTRAINT `fk_partida_has_jugador_partida1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `aceitunas`.`partida` (`partida_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partida_has_jugador_jugador1`
    FOREIGN KEY (`jugador_id`)
    REFERENCES `aceitunas`.`jugador` (`jugador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aceitunas`.`tirada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`tirada` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`tirada` (
  `partida_id` INT UNSIGNED NOT NULL,
  `jugador_id` INT UNSIGNED NOT NULL,
  `distancia` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_tirada_partida_has_jugador1_idx` (`partida_id` ASC, `jugador_id` ASC) VISIBLE,
  PRIMARY KEY (`partida_id`, `jugador_id`),
  CONSTRAINT `fk_tirada_partida_has_jugador1`
    FOREIGN KEY (`partida_id` , `jugador_id`)
    REFERENCES `aceitunas`.`partida_has_jugador` (`partida_id` , `jugador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 13:32:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Table `aceitunas`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aceitunas`.`usuario` ;

CREATE TABLE IF NOT EXISTS `aceitunas`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(45) NULL DEFAULT 'usuario',
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
